# Generated by Django 3.2.5 on 2021-07-12 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100, verbose_name='Firstname')),
                ('lastname', models.CharField(max_length=100, verbose_name='Lastname')),
                ('mobile_phone', models.CharField(max_length=100, verbose_name='Mobile phone')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('department', models.CharField(max_length=100, verbose_name='Department')),
            ],
        ),
    ]
