# Generated by Django 3.2.5 on 2021-07-11 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vueapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactbook',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
