# Generated by Django 3.2.5 on 2021-07-11 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vueapp', '0002_alter_contactbook_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactbook',
            name='phone',
            field=models.TextField(),
        ),
    ]
