# Generated by Django 3.2.5 on 2021-07-11 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vueapp', '0003_alter_contactbook_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactbook',
            name='department',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='contactbook',
            name='phone',
            field=models.CharField(max_length=50),
        ),
    ]
